
spring:
    datasource:
#        url: jdbc:mysql://127.0.0.1:3306/yourDbName
#        username: root
#        password: root
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect