debug: true

spring:
  aop:
    proxy-target-class: true


security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:9070/authserver/oauth/token
      userAuthorizationUri: http://localhost:9070/authserver/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

zuul:
  routes:
    resources:
      path: /resources/**
      url: http://localhost:9071/biblio/hello
    userregiser :
      path: /resource/user/create/**
      url: http://localhost:9071/biblio/api/user/register
    userupdate :
      path: /resource/user/update/**
      url: http://localhost:9071/biblio/api/user/account
    userlist :
      path: /resource/user/listpage/**
      url: http://localhost:9071/biblio/api/user/listpage
#      CATEGORIE RESOURCES
    categoriecreate:
      path: /resource/categorie/create/**
      url: http://localhost:9071/biblio/api/categories/create
    categorieupdate:
      path: /resource/categorie/update/**
      url: http://localhost:9071/biblio/api/categories/update
    categoriesearchepage:
      path: /resource/categorie/searchepage/**
      url: http://localhost:9071/biblio/api/categories/searchepage
    categoriesearche:
      path: /resource/categorie/searche/**
      url: http://localhost:9071/biblio/api/categories/searche
    categorielist:
      path: /resource/categorie/list/**
      url: http://localhost:9071/biblio/api/categories/list
      #      LIVRE RESOURCES
    livrecreate:
      path: /resource/livre/create/**
      url: http://localhost:9071/biblio/api/livres/create
    livreupdate:
      path: /resource/livre/update/**
      url: http://localhost:9071/biblio/api/livres/update
    livresearchepage:
      path: /resource/livre/searchepage/**
      url: http://localhost:9071/biblio/api/livres/searchepage
    livresearche:
      path: /resource/livre/searche/**
      url: http://localhost:9071/biblio/api/livres/searche
      
#      EMPRUNT  RESOURCES
    empruntscreate:
      path: /resource/emprunt/create/**
      url: http://localhost:9071/biblio/api/emprunts/create
    empruntscreatemobile:
      path: /resource/emprunt/createmobile/**
      url: http://localhost:9071/biblio/api/emprunts/createmobile
    empruntsupdate:
      path: /resource/emprunt/update/**
      url: http://localhost:9071/biblio/api/emprunts/update
    empruntssearchepage:
      path: /resource/emprunt/searchepage/**
      url: http://localhost:9071/biblio/api/emprunts/searchepage
    empruntssearche:
      path: /resource/emprunt/searche/**
      url: http://localhost:9071/biblio/api/emprunts/searche
      
#      User info
    userinfo:
      path: /userinfo/**
      url: http://localhost:9071/biblio/user/info
    user:
      path: /user/**
      url: http://localhost:9071/biblio/user
    userpdf:
      path: /pdf/exemple/**
      url: http://localhost:9071/biblio/api/pdf/livre,
    

logging:
  level:
    org.springframework.security: DEBUG